on:
  push:
    branches:
      - main

permissions:
  contents: write
  pull-requests: write

name: release-please

jobs:
  release-please:
    runs-on: ubuntu-latest
    outputs:
      # release: ${{ steps.release }}     
      releases_created: ${{ steps.release.outputs.releases_created }}
      paths_released: ${{ steps.release.outputs.paths_released }}
      prs_created: ${{ steps.release.outputs.prs_created }}
      pr: ${{ steps.release.outputs.pr }}
      prs: ${{ steps.release.outputs.prs }}
    steps:
      - uses: googleapis/release-please-action@v4
        id: release
        with:
          config-file: release-please-config.json
          manifest-file: .release-please-manifest.json
      - name: Show Release Context
        run: |
          echo <<EOF
            ${{ toJSON (steps.release) }}
          EOF
  
  # show-release-please:
  #   needs:
  #     - release-please
  #   runs-on: ubuntu-latest
  #   steps:
  #     - name: Show Release Context
  #       run: |
  #         echo <<EOF
  #           ${{ toJSON (needs.release-please.outputs.releases_created) }}
  #         EOF
